"""empty message

Revision ID: 2e4fe13d807a
Revises: 9f1ea3915650
Create Date: 2024-09-10 13:18:52.955871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4fe13d807a'
down_revision = '9f1ea3915650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_test_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_test_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_test_username'))
        batch_op.drop_index(batch_op.f('ix_users_test_email'))

    op.drop_table('users_test')
    # ### end Alembic commands ###
